@startuml
class AddComponent {
    + type : string
    + <<override>> OnStart() : void
    + <<override>> OnUpdate() : TaskStatus
}
GOAction <|-- AddComponent
AddComponent --> "targetGameobject" GameObject
@enduml
