@startuml
class SendMessage {
    + methodName : string
    + <<override>> OnStart() : void
    + <<override>> OnUpdate() : TaskStatus
}
GOAction <|-- SendMessage
SendMessage --> "targetGameobject" GameObject
@enduml
